### ISSUE TITLE
Feature Request: Always On Top

### ISSUE THREAD

**Issue by Kikketer** [yuhua-chen/LayerX#1]
This app is so close!  I need to match up a UX design pixel perfect to the site that's being built.  I like to overlay what they provided to the website.  I would however like that image to remain floating over as I interact with the browser to tweak the values.

Could you add the feature of "always on top" as another shortcut, or perhaps roll it in with the "lock" functionality?

**Comment by yuhua-chen** [comment]
Thanks for the feedbacks. I'll implement this feature as soon as possible.

**Comment by yuhua-chen** [comment]
Fixed on 4f4e449. Please try latest version. :beers:

**Comment by Kikketer** [comment]
Thanks for the update, however it doesn't seem to be working.  I hit cmd-L and I see the lock icon but when I focus any other window, it still seems to go underneath.  I can't drag the image around while it's locked, which is ok but not what I was intending.  So maybe the request wasn't clear enough, my bad.

Macbook pro: 10.10.5 (14F1605)

**Comment by yuhua-chen** [comment]
Hmm... I'm not sure if the app will have different behaviors in different OS versions. But I understood what you want. Please check if you download the latest release and I'll try to find out.

**Comment by yuhua-chen** [comment]
Sorry. Probably it's my fault that the link of [website](http://yuhua-chen.github.io/LayerX/) was wrong.
I've updated the link and please try the correct version, Thanks.
I put here as well in order that you could download directly.
[https://github.com/yuhua-chen/LayerX/releases/download/v1.1/LayerX.app.zip](https://github.com/yuhua-chen/LayerX/releases/download/v1.1/LayerX.app.zip)

**Comment by Kikketer** [comment]
Yep sorry, I downloaded from the fancier page (github page?) and got version 1.0 (1).  I went to the releases bit in this github project and downloaded the resulting 1.1 zip and installed that app.  I'm now on 1.1 and while I'm typing here the image is floating over the top of chrome which is exactly what I was hoping for.

Thank you!
