### ISSUE TITLE
Does not work on Big Sur 11.6

### ISSUE THREAD

**Issue by logivad** [yuhua-chen/LayerX#30]
<img width="869" alt="Screenshot 2021-09-15 at 12 43 05" src="https://user-images.githubusercontent.com/7761652/133410805-004ac9f8-7706-4fd2-9c19-905339b70592.png">

**Comment by EliotAndres** [comment]
Right click then "Open" solves the issue

**Comment by logivad** [comment]
It helped, thanks @EliotAndres!
