### ISSUE TITLE
Move image outside the top of the screen

### ISSUE THREAD

**Issue by kirkov** [yuhua-chen/LayerX#5]
Hi,

Would it be possible to make the overlay image move outside the screen, on the top ?

**Comment by bensonho** [comment]
Hi, just wanted to say this is a great little app and this feature would make it perfect!

Thank you!

**Comment by yuhua-chen** [comment]
Thanks for feedbacks. I'll put it on my todo list.

**Comment by bensonho** [comment]
Thanks michael!

**Comment by RyanCwynar** [comment]
I'm seeing this issue again. Only applies when dragging with the mouse, keyboard will go beyond top of screen, but that's really slow.

**Comment by damtsnkff** [comment]
Agreed with @RyanCwynar , for long pages it makes it really hard to use. Only moving by 1px up with keyboard isn't really possible in my case.
